### ISSUE TITLE
please add your library to the Arduino Library Manager

### ISSUE THREAD

**Issue by s-light** [sleemanj/JQ8400_Serial#7]
please add your library to the Arduino Library Manager:
https://github.com/arduino/library-registry/blob/main/README.md#adding-a-library-to-library-manager

its fast and benefits the users :-)

[requirements for successful add...](https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-a-library-to-be-added-to-library-manager))

i checked - and currently its not in the [list](https://github.com/arduino/library-registry/blob/main/repositories.txt)

**Comment by sleemanj** [comment]
Not planned.

If somebody else wants to go to the trouble of getting it accepted, they can. Patches (forks, merge requests) welcome.
